services:
  nginx-proxy:
    image: 'nginx:1.27-alpine'
    restart: always
    depends_on:
      swetrix:
        condition: service_healthy
      swetrix-api:
        condition: service_healthy
    links:
      - swetrix-api
      - swetrix
    ports:
      - '80:80'
    command:
      - /bin/sh
      - '-c'
      - "cat > /etc/nginx/conf.d/default.conf << 'EOF'\nserver {\n  listen 80;\n  location /backend/ {\n    proxy_pass http://swetrix-api:5005/;\n    proxy_set_header Host $$host;\n    proxy_set_header X-Real-IP $$remote_addr;\n    proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;\n    proxy_set_header X-Forwarded-Proto $$scheme;\n  }\n  location / {\n    proxy_pass http://swetrix:3000;\n    proxy_set_header Host $$host;\n    proxy_set_header X-Real-IP $$remote_addr;\n    proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;\n    proxy_set_header X-Forwarded-Proto $$scheme;\n  }\n}\nEOF\nnginx -g 'daemon off;'"

  swetrix:
    image: 'swetrix/swetrix-fe:${SWETRIX_VERSION:-v5.2.1}'
    restart: always
    depends_on:
      - swetrix-api
    environment:
      - 'BASE_URL=https://${APP_DOMAIN}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 --spider http://localhost:3000/ping || exit 1'
      interval: 30s
      start_period: 15s

  swetrix-api:
    image: 'swetrix/swetrix-api:${SWETRIX_VERSION:-v5.2.1}'
    restart: always
    environment:
      - 'SECRET_KEY_BASE=${SECRET_KEY_BASE}'
      - 'CLICKHOUSE_HOST=${CLICKHOUSE_HOST}'
      - 'CLICKHOUSE_USER=${CLICKHOUSE_USER}'
      - 'CLICKHOUSE_PORT=${CLICKHOUSE_PORT}'
      - 'CLICKHOUSE_DATABASE=${CLICKHOUSE_DB}'
      - 'CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}'
      - 'REDIS_HOST=${REDIS_HOST}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 --spider http://localhost:5005/ping || exit 1'
      interval: 30s
      start_period: 15s

  redis:
    image: 'redis:7.2-alpine'
    restart: always
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'redis-cli ping | grep PONG'
      interval: 30s
      start_period: 1m

  clickhouse:
    image: 'clickhouse/clickhouse-server:24.3-alpine'
    restart: always
    environment:
      - 'CLICKHOUSE_DB=${CLICKHOUSE_DB}'
      - 'CLICKHOUSE_USER=${CLICKHOUSE_USER}'
      - 'CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1'
      interval: 30s
      start_period: 1m
    cap_add:
      - SYS_NICE
    volumes:
      - 'swetrix-events-dataclean:/var/lib/clickhouse'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  swetrix-events-dataclean:
    driver: local